project:
  type: website
  output-dir: docs   # aqu√≠ le dices a Quarto que genere el sitio en /docs

website:
  title: "Portafolio de Jairo"
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Proyectos"
        href: proyectos.qmd
      - text: "Contacto"
        href: contacto.qmd

format:
  html:
    theme: cosmo

