project:
  type: website
  output-dir: docs   # carpeta donde se genera el sitio

website:
  title: "Portafolio de Jairo"
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Proyectos"
        menu:
          - text: "Mercado mundial de videojuegos"
            href: proyectos/tripleten_videogames_sprint6/tripleten_videogames_intro.qmd
      - text: "Contacto"
        href: contacto.qmd

format:
  html:
    theme: cosmo
    toc: true
    page-layout: full   # ancho completo para gr치ficos
    code-overflow: wrap   # agrega scroll horizontal en bloques de c칩digo
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
          <style>
            /* Gr치ficas: que nunca se recorten */
            img, .quarto-figure {
              max-width: 100% !important;
              height: auto !important;
            }
            /* Bloques de c칩digo: permitir scroll horizontal */
            pre code {
              white-space: pre !important;
              overflow-x: auto !important;
              display: block;
            }
          </style>

execute: 
  fig-width: 8 
  fig-height: 5 
  out-width: 100% 
  code-overflow: wrap