project:
  type: website

website:
  title: "Portafolio de Jairo"
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Proyectos"
        href: proyectos.qmd
      - text: "Contacto"
        href: contacto.qmd

format:
  html:
    theme: cosmo   # puedes cambiar el tema (cosmo, flatly, minty, etc.)
